website/apps/fullcalendar/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import *

from .views import ( CalendarsView, EventSourceView, EventCreateView, CalendarListView, CalendarCreateView,
                     CalendarUpdateView, CalendarDeleteView, EventUpdateView, EventDeleteView )


urlpatterns = patterns('',

    url(r'^$', CalendarsView.as_view(), name='calendars'),

    url(r'^calendar-list/$', CalendarListView.as_view(), name='calendar-list'),
    url(r'^calendar-create/$', CalendarCreateView.as_view(), name='calendar-create'),
    url(r'^calendar-update/$', CalendarUpdateView.as_view(), name='calendar-update'),
    url(r'^calendar-delete/$', CalendarDeleteView.as_view(), name='calendar-delete'),

    url(r'^event-source/$', EventSourceView.as_view(), name='event-source'),
    url(r'^event-create/$', EventCreateView.as_view(), name='event-create'),
    url(r'^event-update/(?P<pk>\d+)/$', EventUpdateView.as_view(), name='event-update'),
    url(r'^event-delete/(?P<pk>\d+)/$', EventDeleteView.as_view(), name='event-delete'),

)

website/urls.py
from django.conf import settings
from django.conf.urls import url, patterns, include

from django.contrib import admin
from .views import HomepageView

admin.autodiscover()

urlpatterns = patterns('',
    (r'^admin/doc/', include('django.contrib.admindocs.urls')),
    (r'^admin/', include(admin.site.urls)),

    url(r'^$', HomepageView.as_view(), name='homepage'),

    url(r'^inplaceeditform/', include('inplaceeditform.urls')),

    url(r'^fullcalendar/', include('apps.fullcalendar.urls', namespace='fullcalendar', app_name='fullcalendar')),
)

if settings.DEBUG:
    urlpatterns = patterns('',
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
        {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
    url(r'', include('django.contrib.staticfiles.urls')),
) + urlpatterns

website/apps/fullcalendar/models.py
# -*- coding: utf-8 -*-
from django.db import models

from schedule.models import Event
from schedule.models.calendars import Calendar

COLOR_TYPE = ( #todo color codes blendig with bootstrap
    ('primary', '#285e8e'),
    ('success', '#398439'),
    ('info', '#269abc'),
    ('warning', '#d58512'),
    ('danger', '#ac2925'),

)
class FullCalendar(Calendar):
    color = models.CharField(max_length=7, choices=COLOR_TYPE)
    nb_slot = models.PositiveIntegerField()

class FullCalendarEvent(Event):
    pass

website/apps/fullcalendar/forms.py
# -*- coding: utf-8 -*-
from django import forms

from .models import FullCalendar, FullCalendarEvent
from website.utils.fields import JqSplitDateTimeField
from website.utils.widgets import JqSplitDateTimeWidget


class FullCalendarEventForm(forms.ModelForm):
    #end_recurring_period = forms.DateTimeField(widget=forms.SplitDateTimeWidget, required=False)
    calendar = forms.ModelChoiceField(queryset=FullCalendar.objects.all(), empty_label=None, required=True)
    start = JqSplitDateTimeField(widget=JqSplitDateTimeWidget(date_format='%d/%m/%Y', attrs={'maxlength':2, 'date_class':'datepicker','time_class':'timepicker'}))
    end = JqSplitDateTimeField(widget=JqSplitDateTimeWidget(date_format='%d/%m/%Y', attrs={'maxlength':2, 'date_class':'datepicker','time_class':'timepicker'}))

    class Meta:
        model = FullCalendarEvent
        fields = ('calendar', 'title', 'description', 'start', 'end', )

        exclude = ('creator', 'created_on', 'end_recurring_period', 'rule', )
        widgets = {
            'title': forms.TextInput(attrs={'class' : 'text'}),
            'description' : forms.Textarea(attrs={'class' : 'desc', 'cols' : 48, 'rows' : 4}),
        }

website/apps/fullcalendar/views.py
# -*- coding: utf-8 -*-
from apps.fullcalendar.models import FullCalendarEvent
from braces.views import CsrfExemptMixin, AjaxResponseMixin, JSONResponseMixin
from datetime import datetime, timedelta

from django.core.urlresolvers import reverse, reverse_lazy
from django.http import Http404
from django.shortcuts import get_object_or_404
from django.template.loader import render_to_string
from django.utils import timezone
from django.utils.html import strip_spaces_between_tags as short
from django.views.generic import ListView, View, CreateView, FormView, UpdateView, DeleteView

from schedule.periods import Month
from schedule.utils import coerce_date_dict
from schedule.views import calendar_by_periods, get_occurrence
from schedule.conf.settings import GET_EVENTS_FUNC, OCCURRENCE_CANCEL_REDIRECT

from .models import FullCalendar
from .forms import FullCalendarEventForm

occtimeformat = 'ST%Y%m%d%H%M%S'

def _encode_occurrence(occ):
    """
        Create a temp id containing event id, encoded id if it is persisted,
        otherwise timestamp.
        Used by AJAX implementations so that JS can assemble a URL
        for calls to occurrence_edit
    """
    if occ.id:
        s = 'ID%d' % occ.id
    else:
        s = occ.start.strftime(occtimeformat)
    return 'E%d_%s' % (occ.event.id, s)


def _decode_occurrence(id):
    """
        reverse of encode_occurrence - given an encoded string
        returns a dict containing event_id and occurrence data
        occurrence data contain either occurrence_id
        or year, month etc.
    """
    try:
        res = {}
        parts = id.split('_')
        res['event_id'] = parts[0][1:]
        occ = parts[1]
        if occ.startswith('ID'):
            res['occurrence_id'] = occ[2:]
        else:
            start = datetime.datetime.strptime(occ, occtimeformat)
            occ_data = dict(year=start.year, month=start.month, day=start.day,
                            hour=start.hour, minute=start.minute, second=start.second)
            res.update(occ_data)
        return res
    except IndexError:
        return

class CalendarsView(ListView):
    context_object_name = 'calendars'
    model = FullCalendar
    template_name = 'fullcalendar/calendars.html'

    def get_context_data(self, **kwargs):
        ctx = super(CalendarsView, self).get_context_data(**kwargs)

        date = coerce_date_dict(self.request.GET)
        if date:
            try:
                date = datetime.datetime(**date)
            except ValueError:
                raise Http404
        else:
            date = timezone.now()

        ctx.update({
            'now' : datetime.now(),
            'date' : date,
        })

        return ctx

class CalendarListView(CsrfExemptMixin, ListView):
    context_object_name = 'calendars'
    model = FullCalendar
    template_name = 'fullcalendar/calendar_list.html'

class CalendarCreateView(CsrfExemptMixin, CreateView):
    context_object_name = 'calendar'
    model = FullCalendar
    template_name = 'fullcalendar/calendar_detail.html'

class CalendarUpdateView(CsrfExemptMixin, UpdateView):
    context_object_name = 'calendar'
    model = FullCalendar
    template_name = 'fullcalendar/calendar_detail.html'

class CalendarDeleteView(CsrfExemptMixin, DeleteView):
    context_object_name = 'calendar'
    model = FullCalendar
    template_name = 'fullcalendar/calendar_detail.html'


class EventSourceView(CsrfExemptMixin, AjaxResponseMixin, JSONResponseMixin, View):
    def post_ajax(self, request, *args, **kwargs):
        try:
            event_list = []
            for event in FullCalendarEvent.objects.filter(calendar__slug=request.POST['calendar_slug']):
                start = datetime.fromtimestamp(float(request.POST['start']), tz=timezone.get_default_timezone())
                end = datetime.fromtimestamp(float(request.POST['end']), tz=timezone.get_default_timezone())
                for occurence in  event.get_occurrences(start, end):
                    event_list.append({
                        'id': _encode_occurrence(occurence),
                        'event_id': event.pk,
                        'title': occurence.title,
                        'start': occurence.start.isoformat(),
                        'end': occurence.end.isoformat(),
                        'recurring': bool(occurence.event.rule),
                        'persisted': bool(occurence.id),
                        'description': occurence.description.replace('\n', '\\n'),
                        'allDay': False,
                        'cancelled': occurence.cancelled,
                    })
        except Exception, e:
            print str(e)
            raise
        finally:
            return self.render_json_response(event_list)

class EventCreateView(CsrfExemptMixin, CreateView):
    context_object_name = 'event'
    form_class = FullCalendarEventForm
    model = FullCalendarEvent
    template_name = 'fullcalendar/event_detail.html'
    success_url = reverse_lazy('fullcalendar:calendars')

    def get_initial(self):
        initial = self.initial.copy()
        if self.request.method == 'GET':
            if self.request.GET.has_key('calendar'):
                initial['calendar'] = self.request.GET['calendar']
            tz = timezone.get_default_timezone()
            initial['start'] = datetime.fromtimestamp(int(self.request.GET['start']), tz=tz)
            initial['end'] = datetime.fromtimestamp(int(self.request.GET['end']), tz=tz)
        return initial

class EventUpdateView(CsrfExemptMixin, UpdateView):
    context_object_name = 'event'
    form_class = FullCalendarEventForm
    model = FullCalendarEvent
    template_name = 'fullcalendar/event_detail.html'
    success_url = reverse_lazy('fullcalendar:calendars')

    def get_object(self, queryset=None):
        obj = super(EventUpdateView, self).get_object(queryset)
        if self.request.method == 'GET':
            day_delta = int(self.request.GET.get('day_delta', 0))
            if self.request.GET.get('action_type', 'clicked') == 'dragged':
                obj.start = obj.start + timedelta(days=day_delta)
            obj.end = obj.end + timedelta(days=day_delta)
        return obj

class EventDeleteView(CsrfExemptMixin, DeleteView):
    context_object_name = 'event'
    model = FullCalendarEvent
    template_name = 'fullcalendar/event_delete.html'
    success_url = reverse_lazy('fullcalendar:calendars')

website/templates/fullcalendar/scripts/calendar.html
<script type='text/javascript'>

    $(document).ready(function () {

        var date = new Date();
        var d = date.getDate();
        var m = date.getMonth();
        var y = date.getFullYear();

        $( ".draggable-calendars .draggable-calendar" ).draggable({
            appendTo: "#calendar",
            helper: "clone"
        });

        $('#calendar').fullCalendar({
            timeFormat: 'H(:mm)',
            firstDay: 1,//monday
            weekMode: 'variable',
            year: {{ date.year }},
            month: {{ date.month }}-1,
            header: {
                left: 'prev,next today',
                center: 'title',
                right: 'month,agendaWeek,agendaDay'
            },
            editable: true,
            droppable: true,
            selectable: true, //Allows a user to highlight multiple days or timeslots by clicking and dragging.
            selectHelper: true,

            viewDisplay: function (view) {
                $('#calendar').fullCalendar('refetchEvents');
            },

            eventSources: [
                {% for cal in calendars %}
                {
                    url: '{% url 'fullcalendar:event-source' %}',
                    type: 'POST',
                    data: {
                        calendar_slug: '{{ cal.slug }}'
                    },
                    color: '{{ cal.get_color_display }}'
                }{% if forloop.last %}{% else %},{% endif %}
                {% endfor %}
            ],

            eventRender: function(event, element) {
                var del_url = "{% url 'fullcalendar:event-delete' 0 %}".replace(0, event['event_id']);
                element.children(".fc-event-inner").append("<span><a class=\"fc-event-delete\" href=\""+del_url+"\">X</a></span>");

            },

            select: function (startDate, endDate, allDay, jsEvent, view) {
                if (view.name = 'month') {
                    startDate.setHours(12);
                    startDate.setMinutes(00);
                    endDate.setHours(12);
                    endDate.setMinutes(30);
                }
                var start = Math.round(startDate.getTime() / 1000);
                var end = Math.round(endDate.getTime() / 1000);
                var url = '{% url 'fullcalendar:event-create' %}';
                $.facebox(function(){
                    $.get(
                            "{% url 'fullcalendar:event-create' %}",
                            {
                                'start': start,
                                'end': end
                            },
                            function (data, textStatus, jqXHR) {
                                $.facebox(data);
                            },
                            'html'
                    );
                });
            },

            drop: function(date, allDay) {
                console.log("dropped");
                var calendar_pk = $(this).attr('data-id');
                var start = Math.round(date.getTime() / 1000);
                var end = Math.round(date.getTime() / 1000);
                var url = '{% url 'fullcalendar:event-create' %}';
                $.facebox(function(){
                    $.get(
                            "{% url 'fullcalendar:event-create' %}",
                            {
                                'calendar': calendar_pk,
                                'start': start,
                                'end': end
                            },
                            function (data, textStatus, jqXHR) {
                                $.facebox(data);
                            },
                            'html'
                    );
                });
            },

            eventClick: function (event, element) {
                $.facebox(function(){
                    $.get(
                            "{% url 'fullcalendar:event-update' 0 %}".replace(0, event['event_id']),
                            {},
                            function (data, textStatus, jqXHR) {
                                $.facebox(data);
                            },
                            'html'
                    );
                });
            },

            eventDrop: function(event, dayDelta, minuteDelta, allDay, revertFunc, jsEvent, ui, view) {
                $.facebox(function(){
                    $.get(
                            "{% url 'fullcalendar:event-update' 0 %}".replace(0, event['event_id']),
                            {
                                'action_type': 'dragged',
                                'day_delta': dayDelta
                            },
                            function (data, textStatus, jqXHR) {
                                $.facebox(data);
                            },
                            'html'
                    );
                });
            },

            eventResize: function( event, dayDelta, minuteDelta, revertFunc, jsEvent, ui, view ) {
                $.facebox(function(){
                    $.get(
                            "{% url 'fullcalendar:event-update' 0 %}".replace(0, event['event_id']),
                            {
                                'action_type': 'resized',
                                'day_delta': dayDelta
                            },
                            function (data, textStatus, jqXHR) {
                                $.facebox(data);
                            },
                            'html'
                    );
                });
            }

        });
    });

</script>

website/templates/fullcalendar/scripts/event_create.html
<script type='text/javascript'>
    $("input[name^='date']").datepicker();
    $("input[name^='time']").timepicker();
</script>

website/templates/fullcalendar/scripts/event_detail.html
<script type='text/javascript'>
    $("input[name^='date']").datepicker();
    $("input[name^='time']").timepicker();
</script>